/*
  HOLOCRÓN GALÁCTICO — Lugares, batallas, cronología, glosario y registro de canon
  {llaves} = detalle propuesto, pendiente de aprobación.
  Coordenadas del mapa: top/left en %, como en la web original.
*/
window.LORE = window.LORE || {};

/* ------------------------------------------------------------ LUGARES */
LORE.lugares = [
  { id: 'rilur-prime', nombre: 'Rilur Prime', faccion: 'rilur', afiliacion: 'Imperio de Rilur', top: 50, left: 50, src: 'O',
    tipo: 'Capital imperial',
    texto: 'Centro del Imperio de Rilur. {Escenario del duelo entre Kemet y el Primer Emperador.} Allí se proclama heredero Arlik.' },
  { id: 'dubitsa-prime', nombre: 'Dubitsa Prime', faccion: 'dubitsa', afiliacion: 'Imperio de Dubitsa', top: 30, left: 75, src: 'O',
    tipo: 'Capital imperial · ciudad de Instantinopla',
    texto: 'Corazón de Dubitsa. Su gran ciudad es Instantinopla, sede del trono y de las universidades. Absorbida por Rilur en el Tomo I, restaurada por Teosio II, conquistada por Muwiya y liberada por la Coalición Definitiva.' },
  { id: 'vinica-prime', nombre: 'Vinica Prime', faccion: 'vinica', afiliacion: 'República de Vinica', top: 70, left: 25, src: 'O',
    tipo: 'Capital republicana · sede del Senado',
    texto: 'Capital de la República. Liberada por la campaña de Kefra tras la destrucción del Reactor Oscuro. {Allí se firmó el pacto de la Coalición Definitiva.}' },
  { id: 'polus-12', nombre: 'Polus-12', faccion: 'vinica', afiliacion: 'República de Vinica', top: 81, left: 33, src: 'A',
    tipo: 'Mundo industrial',
    texto: 'Gran mundo industrial de Vinica, liberado junto con Vinica Prime. {Sus fábricas abastecieron a la rebelión y a la Coalición.}' },
  { id: 'union-este', nombre: 'Unión del Este', faccion: 'principados', afiliacion: 'Principados del Este', top: 75, left: 80, src: 'O',
    tipo: 'Sede de la confederación',
    texto: 'Centro de los Principados del Este unificados. {Sede del Consejo de Príncipes.}' },
  { id: 'arcados', nombre: 'Arcados', faccion: 'neutral', afiliacion: 'Mundo neutral (origen de Kefra)', top: 15, left: 15, src: 'O',
    tipo: 'Mundo-bosque neutral',
    texto: 'Mundo neutral del noroeste lejano y lugar de origen de Kefra, donde lo encontró Raqid. {Está cubierto de bosques antiguos y es uno de los accesos al otro plano.}' },
  { id: 'portus', nombre: 'Portus', faccion: 'andalus', afiliacion: 'Antigua capital de Andalus', top: 45, left: 90, src: 'O',
    tipo: 'Antigua capital · puerta del Vacío',
    texto: 'Antigua capital de Andalus en esta galaxia. {Allí proclamó Muwiya el Gaziato. Está junto al Paso del Vacío. Quedó abandonada tras la derrota de Rahman.}' },
  { id: 'riqtom', nombre: 'Riqtom', faccion: 'sintonia', afiliacion: 'Santuario de la Sintonía', top: 85, left: 55, src: 'O',
    tipo: 'Santuario',
    texto: 'Santuario de los Caballeros de la Sintonía. {Refugio de la orden después de Lolop. Allí murió Saelen Vharr y allí se formó Kemet.}' },
  { id: 'lolop', nombre: 'Lolop (Orion-34)', faccion: 'rilur', afiliacion: 'Sistema Orion-34', top: 35, left: 63, src: 'A',
    tipo: 'Planeta de batalla',
    texto: 'Planeta principal del sistema Orion-34, donde la coalición de Vinica, Dubitsa y la Sintonía se enfrentó al expansionismo de Rilur y Saelen Vharr derrotó a Lord Veylan. {Escenario también de la Segunda Batalla de Orion-34, donde murió Muwiya.}' },
  { id: 'raqut', nombre: 'Raqut', faccion: 'rilur', afiliacion: 'Imperio de Rilur', top: 54, left: 66, src: 'A',
    tipo: 'Mundo del Reactor Oscuro',
    texto: 'Mundo donde estaba el Reactor Oscuro, destruido por Kefra. {Es un mundo herido en el paso hacia el núcleo, donde Reus cayó para frenar a Andalus.}' },
  { id: 'rilit', nombre: 'Rilit', faccion: 'rilur', afiliacion: 'Imperio de Rilur', top: 39, left: 43, src: 'A',
    tipo: 'Luna-forja',
    texto: 'Luna-forja con la mega-instalación militar que destruyó la facción rebelde en el Tomo II. {Reconstruida con Reus para funcionar con energía limpia. Allí venció Ublek a Vakel.}' },
  { id: 'uxal', nombre: 'Uxal', faccion: 'rilur', afiliacion: 'Imperio de Rilur (recuperado)', top: 20, left: 40, src: 'O',
    tipo: 'Mundo rebelde',
    texto: 'Foco de la rebelión del interregno. La victoria de Arlik en Uxal consolidó su legitimidad.' },
  { id: 'turonis', nombre: '{Turonis}', faccion: 'neutral', afiliacion: 'Campo de batalla', top: 63, left: 72, src: 'P',
    tipo: 'Mundo estratégico',
    texto: '{Cruce de rutas entre Portus, el núcleo y el sur. Escenario de la batalla apocalíptica en la que la Coalición Definitiva derrotó al Príncipe Rahman.}' },
  { id: 'paso-vacio', nombre: '{Paso del Vacío}', faccion: 'andalus', afiliacion: 'Hacia la galaxia de Andalus', top: 52, left: 97, src: 'P',
    tipo: 'Corredor intergaláctico',
    texto: '{Único corredor conocido hacia la galaxia de Andalus, más allá de Portus. Por él pasaron la invasión de Korvan y las de Muwiya y Rahman.}' }
];

/* ------------------------------------------------------------ BATALLAS Y ACONTECIMIENTOS */
LORE.batallas = [
  { id: 'lolop', nombre: 'Batalla de Orion-34 (Lolop)', anio: 0, tomo: 'I', lugar: 'lolop',
    bandos: 'Coalición (Vinica, Dubitsa, Caballeros de la Sintonía) contra Rilur',
    mandos: 'Saelen Vharr · Lord Veylan',
    resultado: 'Victoria de la coalición. Saelen Vharr derrota a Lord Veylan.',
    consecuencias: 'Victoria agridulce: Rilur rodea el frente y conquista el este, incluida Dubitsa.' },
  { id: 'rilit-sabotaje', nombre: 'Destrucción de Rilit', anio: 18, tomo: 'II', lugar: 'rilit',
    bandos: 'Facción rebelde contra Rilur',
    mandos: '{Células de Kemet}',
    resultado: 'Destruida la mega-instalación militar imperial.',
    consecuencias: 'La ira del Emperador: aparecen los Nighul.' },
  { id: 'duelo-rilur-prime', nombre: 'Duelo de Kemet y el Emperador', anio: 18, tomo: 'II', lugar: 'rilur-prime',
    bandos: 'Caballeros de la Sintonía contra el Emperador de Rilur',
    mandos: 'Kemet · {Sarkon}',
    resultado: 'Mueren los dos.',
    consecuencias: 'Gran crisis del centro imperial. {Korvan toma el trono.} Raqid parte a buscar al Guardián del Bosque.' },
  { id: 'reactor-raqut', nombre: 'Destrucción del Reactor Oscuro', anio: 25, tomo: 'III', lugar: 'raqut',
    bandos: 'Kefra {y Raqid} contra los Nighul',
    mandos: 'Kefra',
    resultado: 'Reactor Oscuro destruido.',
    consecuencias: 'Rilur pierde la energía casi ilimitada. {Los Nighul quedan rotos.} Se abre el camino para liberar Vinica.' },
  { id: 'liberacion-vinica', nombre: 'Liberación de Vinica Prime y Polus-12', anio: 26, tomo: 'III', lugar: 'vinica-prime',
    bandos: 'Rebelión de Kefra contra la guarnición de Rilur',
    mandos: 'Kefra',
    resultado: 'Vinica Prime y Polus-12 liberados.',
    consecuencias: 'Kefra se convierte en símbolo de esperanza. Vinica vuelve a ser libre.' },
  { id: 'invasion-andalus', nombre: 'Invasión de la galaxia de Andalus', anio: 28, tomo: 'IV', lugar: 'paso-vacio',
    bandos: 'Rilur contra Andalus',
    mandos: '{Korvan}',
    resultado: 'Desastre: Rilur pierde millones de tropas y casi nadie vuelve.',
    consecuencias: 'Rilur pierde gran parte de su ejército. Andalus conoce el camino y acumula rencor.' },
  { id: 'contraofensiva-korvan', nombre: 'Contraofensiva de Korvan', anio: 29, tomo: 'IV', lugar: 'rilur-prime',
    bandos: 'Rilur contra los mundos rebeldes',
    mandos: '{Korvan}',
    resultado: 'Represión brutal.',
    consecuencias: 'Empuja a más mundos a la rebelión.' },
  { id: 'guerra-civil', nombre: 'Guerra civil galáctica', anio: 30, tomo: 'IV', lugar: 'rilur-prime',
    bandos: 'Kefra y los pueblos sometidos contra Rilur',
    mandos: 'Kefra · Teosio II',
    resultado: 'Rilur pierde el control de la galaxia.',
    consecuencias: 'Dubitsa renace y Vinica se fortalece. Lleva a la tregua de Reus.' },
  { id: 'caida-dubitsa-prime', nombre: 'Caída de Dubitsa Prime', anio: 53, tomo: 'VI', lugar: 'dubitsa-prime',
    bandos: 'Andalus contra Dubitsa',
    mandos: 'Muwiya · Teosio II',
    resultado: 'Muwiya conquista Dubitsa Prime.',
    consecuencias: '{Teosio II huye con su corte y sus Pretoni.}' },
  { id: 'guardia-raqut', nombre: '{Última Guardia de Raqut}', anio: 55, tomo: 'VI', lugar: 'raqut',
    bandos: 'Rilur contra Andalus',
    mandos: 'Reus · Muwiya',
    resultado: 'Reus cae, pero gana tiempo.',
    consecuencias: 'Ublek toma el mando con el Imperio ya movilizado.' },
  { id: 'rilit-vakel', nombre: '{Batalla de Rilit}', anio: 55, tomo: 'VI', lugar: 'rilit',
    bandos: 'Rilur contra Andalus',
    mandos: 'Ublek · Vakel',
    resultado: 'Ublek derrota a Vakel.',
    consecuencias: 'Las forjas del Imperio se salvan y Ublek pasa a la ofensiva.' },
  { id: 'orion-34-ii', nombre: '{Segunda Batalla de Orion-34}', anio: 56, tomo: 'VI', lugar: 'lolop',
    bandos: 'Rilur contra Andalus',
    mandos: 'Ublek · Muwiya',
    resultado: 'Andalus es repelido y Muwiya muere.',
    consecuencias: 'Provoca la Expedición de Venganza del Príncipe Rahman.' },
  { id: 'liberacion-instantinopla', nombre: 'Liberación de Dubitsa Prime', anio: 57, tomo: 'VI', lugar: 'dubitsa-prime',
    bandos: 'Coalición Definitiva contra Andalus',
    mandos: 'Teosio II · Ublek · Kefra',
    resultado: 'Dubitsa Prime liberada.',
    consecuencias: 'Instantinopla vuelve a manos de Teosio II.' },
  { id: 'turonis', nombre: '{Batalla de Turonis}', anio: 58, tomo: 'VI', lugar: 'turonis',
    bandos: 'Coalición Definitiva (Dubitsa, Vinica, Rilur, Kefra) contra la Expedición de Venganza',
    mandos: 'Ublek · Teosio II · Kefra · Rahman',
    resultado: 'Batalla apocalíptica. Rahman es derrotado.',
    consecuencias: 'Andalus se desintegra. Kefra desaparece. Ublek queda gravemente herido.' },
  { id: 'uxal', nombre: 'Campaña de Uxal', anio: 67, tomo: 'VII', lugar: 'uxal',
    bandos: 'Arlik contra la rebelión de Uxal {(apoyada por Moffs)}',
    mandos: 'Arlik · Trok',
    resultado: 'Victoria decisiva de Arlik pese a la inferioridad numérica.',
    consecuencias: 'Arlik consolida su legitimidad y empieza la guerra por el dominio total del Imperio.' }
];

/* ------------------------------------------------------------ CRONOLOGÍA */
LORE.cronologia = [
  { anio: 'Siglos AO', texto: 'Rilur es la fuerza dominante de la galaxia. Dubitsa es una civilización ancestral. Vinica es una democracia comercial. Los Caballeros de la Sintonía protegen el equilibrio.', tomo: null, src: 'O' },
  { anio: '{Siglos AO}', texto: '{Los antepasados de Andalus viven en esta galaxia, con Portus como capital, y se marchan por el Paso del Vacío.}', tomo: null, src: 'P' },
  { anio: '{c. 30 AO}', texto: 'Rilur enciende el Reactor Oscuro {en Raqut}. La Sintonía empieza a desafinarse.', tomo: 'I', src: 'A' },
  { anio: 'c. 12 – 1 AO', texto: 'Guerra de las Galaxias Fragmentadas: Rilur avanza imparable con clones y droides. Vinica se alía con los Caballeros y con Dubitsa.', tomo: 'I', src: 'O' },
  { anio: '0', texto: 'Batalla de Orion-34 en Lolop: Saelen Vharr derrota a Lord Veylan.', tomo: 'I', src: 'O' },
  { anio: '0 – 1 DO', texto: 'Cae el este, incluida Dubitsa. Vinica firma un tratado humillante {(la Paz de Hierro)}.', tomo: 'I', src: 'O' },
  { anio: '{c. 8 DO}', texto: '{Muere Saelen Vharr. Kemet hereda la orden.}', tomo: 'II', src: 'P' },
  { anio: '{18 DO}', texto: 'La facción rebelde destruye Rilit. Aparecen los Nighul. Kemet y el Emperador mueren en duelo. {Korvan toma el trono.}', tomo: 'II', src: 'O' },
  { anio: '{23 DO}', texto: 'Cinco años después, Raqid encuentra a Kefra en Arcados.', tomo: 'III', src: 'O' },
  { anio: '{25 DO}', texto: 'Kefra destruye el Reactor Oscuro.', tomo: 'III', src: 'O' },
  { anio: '{26 DO}', texto: 'Liberación de Vinica Prime y Polus-12.', tomo: 'III', src: 'O' },
  { anio: '{28 DO}', texto: 'Desastrosa invasión de la galaxia de Andalus. Casi nadie vuelve.', tomo: 'IV', src: 'O' },
  { anio: '{29 – 33 DO}', texto: 'Contraofensiva brutal y guerra civil galáctica total. Dubitsa renace con Teosio II.', tomo: 'IV', src: 'O' },
  { anio: '{33 DO}', texto: 'Muere el Emperador {Korvan}. Reus sube al trono, firma la tregua y crea el Parlamento.', tomo: 'V', src: 'O' },
  { anio: '{33 – 52 DO}', texto: 'Era de reconstrucción y energía limpia.', tomo: 'V', src: 'O' },
  { anio: '{52 DO}', texto: 'Los Hijos de Andalus invaden, liderados por el General Muwiya.', tomo: 'VI', src: 'O' },
  { anio: '{53 DO}', texto: 'Muwiya conquista Dubitsa Prime.', tomo: 'VI', src: 'A' },
  { anio: '{55 DO}', texto: 'Reus cae en sacrificio. Ublek toma el mando y derrota a Vakel.', tomo: 'VI', src: 'O' },
  { anio: '{56 DO}', texto: 'Ublek repele a Andalus y muere Muwiya.', tomo: 'VI', src: 'A' },
  { anio: '{57 DO}', texto: 'Llega la Expedición de Venganza del Príncipe Rahman. Se forma la Coalición Definitiva, que libera Dubitsa Prime.', tomo: 'VI', src: 'O' },
  { anio: '{58 DO}', texto: 'Batalla apocalíptica {de Turonis}: Rahman es derrotado. Kefra desaparece.', tomo: 'VI', src: 'O' },
  { anio: '{c. 59 DO}', texto: '{Los principados del este se unifican.}', tomo: 'VI', src: 'P' },
  { anio: '{c. 62 DO}', texto: '{Muere Teosio II y le sucede Teosio III.}', tomo: 'VI', src: 'P' },
  { anio: '{64 DO}', texto: 'Muere Ublek y deja el trono vacío.', tomo: 'VI', src: 'O' },
  { anio: '{64 – 67 DO}', texto: 'Interregno: Moffs y almirantes compiten por el trono y las regiones lejanas se declaran autónomas.', tomo: 'VII', src: 'O' },
  { anio: '{67 DO}', texto: 'Arlik vuelve del exilio con Trok y vence en Uxal.', tomo: 'VII', src: 'O' },
  { anio: '{68 DO} · Presente', texto: 'Frágil equilibrio de poder. Arlik purga a sus comandantes y Dubitsa asciende.', tomo: 'VII', src: 'O' }
];

/* ------------------------------------------------------------ GLOSARIO */
LORE.glosario = [
  { t: 'Sintonía Universal', d: 'La energía que conecta todas las cosas. Los Caballeros buscan el equilibrio en ella.', src: 'O' },
  { t: 'Caballeros de la Sintonía', d: 'Orden ancestral de monjes guerreros, hoy casi extinta. También se les llama Caballeros Ocultos. Su sintonía se basa en la sintonía del universo.', src: 'O' },
  { t: 'Reactor Oscuro', d: 'Creación de Rilur que le daba energía y recursos casi ilimitados a un coste casi nulo. Permitía ejércitos masivos casi gratuitos. Su energía alterada desafinaba la Sintonía del universo y potenciaba a los Nighul. Kefra lo destruyó.', src: 'A' },
  { t: 'Nighul', d: 'La élite de la élite de Rilur. Cada uno equivale a cien Nizarios. Se seleccionan genéticamente entre guerreros y clones, con un entrenamiento inhumano y años de veteranía. También son científicos, filósofos e ingenieros. En el Tomo II aparecen escritos como «Nizghul», una errata.', src: 'A' },
  { t: 'Nizarios', d: 'La élite del ejército de Rilur. Junto a los Nighul, el orgullo del Imperio. En algunas notas aparecen como «Nizaríes».', src: 'O' },
  { t: 'Pretoni', d: 'Guerreros de élite de Dubitsa, numerosos, leales y temidos en toda la galaxia.', src: 'O' },
  { t: 'Clones y droides', d: 'La base de los ejércitos masivos de Rilur.', src: 'O' },
  { t: 'Moffs', d: 'Grandes mandos regionales de Rilur. {Son gobernadores con flotas propias.} Se disputaron el trono en el interregno.', src: 'O' },
  { t: 'Parlamento de Rilur', d: 'Creado por Reus. Dio a Arlik un respaldo débil.', src: 'O' },
  { t: 'Senado de Vinica', d: 'Órgano de gobierno de la República. Cree que la fortaleza económica es la mejor defensa.', src: 'O' },
  { t: 'Hijos de Andalus', d: 'El pueblo de Andalus, originario de otra galaxia.', src: 'O' },
  { t: 'Gaziato de Andalus', d: 'La potencia teocrático-militar de Andalus. {Muwiya lo proclamó en Portus como su dominio en esta galaxia.}', src: 'O' },
  { t: 'Expedición de Venganza', d: 'Campaña del Príncipe Rahman para vengar la muerte de Muwiya. Termina con su derrota ante la Coalición Definitiva.', src: 'A' },
  { t: 'Coalición Definitiva', d: 'Alianza de Dubitsa, Vinica y Rilur (con Kefra) contra Rahman.', src: 'O' },
  { t: 'Guardián del Bosque', d: 'Título profetizado por Kemet y que llevó Kefra.', src: 'O' },
  { t: 'Otro plano', d: 'Donde se entrenó Kefra. {Los Caballeros lo llaman Plano de la Resonancia: un reflejo de la realidad hecho de Sintonía pura, donde el tiempo corre distinto.}', src: 'O' },
  { t: '{Paso del Vacío}', d: '{Corredor intergaláctico entre esta galaxia y la de Andalus, junto a Portus.}', src: 'P' },
  { t: '{Paz de Hierro}', d: '{Nombre del tratado humillante que firmó Vinica en el Tomo I.}', src: 'P' },
  { t: '{Tregua de Instantinopla}', d: '{Nombre de la tregua de Reus con Dubitsa y Vinica.}', src: 'P' },
  { t: 'Última Gran Guerra', d: 'La guerra contra Andalus del Tomo VI.', src: 'O' },
  { t: 'Era de las Grandes Guerras y sus Ecos', d: 'El periodo que narra el Holocrón.', src: 'O' },
  { t: '{DO / AO}', d: '{Calendario de trabajo: años Después y Antes de Orion. El año 0 es la Batalla de Orion-34.}', src: 'P' }
];

/* ------------------------------------------------------------ REGISTRO DE CANON */
LORE.canon = {
  fuentes: [
    { nombre: 'Web original (7 Tomos)', url: 'https://crepi-alkam.neocities.org/', nota: 'Texto literal recuperado el 2 oct 2026.' },
    { nombre: 'Versión anterior (6 Tomos)', url: 'https://crepi-alkam.neocities.org/FICCION-GALACTICA.html', nota: 'Rilur «Fragmentado»: los Moffs y almirantes antes de Arlik.' },
    { nombre: 'Notas de reconstrucción', url: '', nota: 'lore_rilur_dubitsa_reconstruccion.md y lore_rilur_eventos_batallas_protagonistas.md (memoria de conversaciones; menor fiabilidad).' }
  ],
  decisiones: [
    { p: '¿Quién es el Emperador de los Tomos III–V?', r: 'Un sucesor distinto del Primer Emperador (que muere con Kemet). Es el padre de Reus.' },
    { p: 'Nizghul, Nighul y Nizarios', r: '«Nizghul» es una errata de Nighul. Los Nizarios son otro cuerpo.' },
    { p: 'Caballeros Oscultos', r: 'Es otro nombre de los Caballeros de la Sintonía (Caballeros Ocultos). Su sintonía se basa en la del universo.' },
    { p: 'Destino de Kefra', r: 'Lucha contra Rahman y desaparece.' },
    { p: 'Lord Veylan', r: 'Señor de la guerra de Rilur, sin poderes de la Sintonía.' },
    { p: 'Vakel', r: 'General de Andalus, derrotado por Ublek.' },
    { p: 'Dubitsa Prime', r: 'Muwiya la conquistó y después fue liberada.' },
    { p: 'Nombres de los emperadores', r: 'Claude propone nombres (Sarkon y Korvan), pendientes de aprobar.' },
    { p: 'Lugares de las notas', r: 'Se mantienen Polus-12, Instantinopla, Lolop, Raqut y Rilit con los papeles propuestos.' },
    { p: 'Reactor Oscuro', r: 'Energía y recursos casi ilimitados a coste casi nulo: ejércitos masivos casi gratis y expansión. Su energía alterada desafinaba la Sintonía del universo. Por eso la orden se unió a Vinica y Dubitsa en Lolop.' },
    { p: 'Nighul después del reactor', r: 'Guerreros y clones de selección genética, entrenamiento inhumano y años de veteranía. El reactor potenciaba sus poderes arcanos. Después siguieron siendo una élite temida y además científicos, filósofos e ingenieros. Junto a los Nizarios, el orgullo de Rilur.' },
    { p: 'Batalla contra Rahman', r: 'En otro planeta estratégico, donde chocan el avance de Andalus y la Coalición. Claude propone Turonis.' },
    { p: 'Motivo de la Expedición de Venganza', r: 'La muerte de Muwiya. La expedición de Rilur a Andalus fue una masacre de la que casi nadie volvió.' },
    { p: 'Teosio II', r: 'Restauró Dubitsa, luchó en la Coalición y es padre de Teosio III.' },
    { p: 'Alid', r: 'Probablemente un hijo del Emperador de Andalus que llevó una campaña de venganza. En segundo plano.' },
    { p: 'Formato', r: 'Crónica narrada con fichas.' }
  ],
  propuestas: [
    'Nombres de los emperadores: Sarkon (el Primer Emperador) y Korvan (Gran Mariscal y sucesor).',
    'Calendario DO/AO, con el año 0 en la Batalla de Orion-34, y todas las fechas concretas.',
    'Turonis como lugar de la batalla final contra Rahman, y la muerte de Rahman en ella.',
    'El Paso del Vacío como corredor hacia la galaxia de Andalus, junto a Portus.',
    'Los antepasados de Andalus vivieron en esta galaxia con capital en Portus.',
    'Muwiya proclama el Gaziato en Portus. Muere en la Segunda Batalla de Orion-34.',
    'Reus cae en la Última Guardia de Raqut. Ublek vence a Vakel en Rilit.',
    'Paz de Hierro (tratado de Vinica) y Tregua de Instantinopla (tregua de Reus).',
    'Linaje de maestros: Saelen Vharr → Kemet → Raqid → Kefra.',
    'El Plano de la Resonancia como nombre del «otro plano».',
    'La madre de Arlik era una ingeniera Nighul. Trok es un veterano de la época del reactor.',
    'El Primer Emperador estaba unido al reactor, lo que explica que pudiera enfrentarse a Kemet.',
    'Korvan invade Andalus para sustituir los recursos del reactor.',
    'La unificación de los Principados se produce después de Turonis (c. 59 DO).',
    'Lemas de las facciones y títulos honoríficos (el Implacable, el Reformador, el Defensor).'
  ],
  pendientes: [
    '¿Cuál es el verdadero nombre del Emperador de Andalus? ¿Cómo se llama su galaxia?',
    '¿Qué campaña libró el Príncipe Alid y cuándo?',
    '¿Vakel murió o fue capturado?',
    '¿Qué fue de Raqid después de Raqut?',
    '¿Quién gobierna Vinica (cancilleres) y quiénes son los príncipes de la Unión del Este?',
    '¿Cómo se llama la ciudad capital de Rilur Prime?',
    '¿Qué era exactamente la «legión secreta» de Arlik?',
    '¿Quién es la madre de Arlik?',
    '¿Hay más Tomos después del VII?',
    'Raqut y Rilit: ¿el autor los recordaba con otros papeles?',
    'Instantinopla: confirmar su ortografía.'
  ]
};
